### ISSUE TITLE
Undo the changes to i2b2 default database types

### ISSUE THREAD

**Issue by Fasjul** [tuneinsight/geco-i2b2-data-source#22]
The changes done in this file: https://github.com/tuneinsight/geco-i2b2-data-source/blob/c2333ea39ae11582c363a4be762104c4dc4ec773/build/package/i2b2/sql/10-i2b2-modifications.sh

 to CONCEPT_CD, ENCOUNTER_NUM, TVAL_CHAR should be rolled back. (NOT the first two that are path lengths, these are fine)
Reason: the OBSERVATION_FACT table content is copied by i2b2 in a temporary table (called DX or whatever) which uses default types and sizes and is therefore not affected by the changes done here.

So what happens with those changes is they allow writing crazy values (such as long texts or bigints) in the i2b2 star schema tables with no error message, but upon the first query i2b2 tries to copy those values in the temporary table which fields do not fit. DX table cannot be created, and i2b2 returns a cryptic error.
I found no evidence for a possibility to modify the DX temporary table columns. Having integers for encounter numbers, and 255 as max length for text values should be kept as a strict constraint.

**Comment by f-marino** [comment]
fixed by [a3423f1](https://github.com/tuneinsight/geco-i2b2-data-source/commit/a3423f16b2799c0285ae32e4e0692fc71cb47e70)
